### ISSUE TITLE
Error on install database

### ISSUE THREAD

**Issue by agusesetiyono** [khodakhah/nodcms#1]
Got the message "There has been attempt to setup the database on nodcms but failed!", can't solve on retry instalation.

**Comment by khodakhah** [comment]
This Error related to your host's access to database.
Unfortunately the installation doesn't work so good in this version!
You can try manual installation:
1. Use <strong><span style="color:red;">[cms directory]</span>/install/installer/masks/nodcms.sql</strong> and make your database.
2. Make a file <strong>"database.php"</strong> in <strong><span style="color:red;">[cms directory]</span>/frontend/config/</strong> and copy the below text with your parameters:

```
<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$active_group = 'default';
$active_record = TRUE;

$db['default']['hostname'] = 'localhost'; // Your host name
$db['default']['username'] = 'root'; // Your Database username
$db['default']['password'] = ''; // Your Database password
$db['default']['database'] = 'nodcms'; // Name of The Database that you make it
$db['default']['dbdriver'] = 'mysql';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = TRUE;
$db['default']['db_debug'] = TRUE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
$db['default']['swap_pre'] = '';
$db['default']['autoinit'] = TRUE;
$db['default']['stricton'] = FALSE;
```
3. Copy <strong><span style="color:red;">[cms directory]</span>/frontend/config/database.php</strong> to <strong><span style="color:red;">[cms directory]</span>/backend/config/</strong>

**Comment by agusesetiyono** [comment]
okay done.
Now how to login? there are no credential info for login

**Comment by khodakhah** [comment]
The username is <strong>admin</strong>
I forgot the password, but you can replace <strong>e10adc3949ba59abbe56e057f20f883e</strong> instead of the admin's password in Database to change password to <strong>123456</strong>

**Comment by methakon** [comment]
i cant even import database 
it is giving error 
#1054 - Unknown column 'Column 24' in 'field list'

**Comment by khodakhah** [comment]
Sorry! The file had a bug, but I fixed it.
Check the below link:
https://github.com/khodakhah/nodcms/commit/fd2ecc73a07e4aa288f339dbd2425307f899a2af

**Comment by okiewardoyo** [comment]
Same with me, today i want to install on my server but it says "There has been attempt to setup the database on tokm4153_nodcms but failed!"

**Comment by okiewardoyo** [comment]
Solved.
1. Run nodcms.sql from [cms directory]/install/installer/masks/nodcms.sql on your database
2. Make a file "database.php" in [cms directory]/**nodcms**/config/ 
3. Rename install directory,

**Comment by nonconforme** [comment]
Replace [cms directory]/install/installer/masks/nodcms.sql file with this one and setup will be fixed

[nodecms-sql-fix.zip](https://github.com/khodakhah/nodcms/files/549777/nodecms-sql-fix.zip)

**Comment by khodakhah** [comment]
New version of NodCMS updated.
