### ISSUE TITLE
Register not working

### ISSUE THREAD

**Issue by csiber** [khodakhah/nodcms#10]
Register module not workable. Im register my site, but after register jumping to blank screen. The error.log nothing write error messages. The sql query is work, email sending not work, no jumping to the register complete page.

**Comment by khodakhah** [comment]
Hi,
Thank you for your "bug report".
I had <strong>debug</strong> it! You can see changes in below link: 
https://github.com/khodakhah/nodcms/commit/b1e02f1934879eaa8905890534fa37dc34c0e472

**Comment by csiber** [comment]
Okay. Thank you.

**Comment by khodakhah** [comment]
New version of NodCMS updated.
