### ISSUE TITLE
Load extension_more in extension_detail

### ISSUE THREAD

**Issue by rifal89** [khodakhah/nodcms#12]
Hi,

How i can load data from extension_more in extension_detail page? 

Thanks

**Comment by khodakhah** [comment]
Hi,
After set your extra fields in `nodcms/page_type.yml`, you need just use it in your view files.
For example: for "Pricing tables" you can see in this file `nodcms/views/nodcms_general/page_type/pricing_table_preview.php`, how I used **extension_more** 
`$item['extension_more']["row1"]`
Just such as a simple offset!

Coming soon I will write some full guidance about **page_type.yml** in [nodcms.com](http://www.nodcms.com)

**Comment by khodakhah** [comment]
New version of NodCMS updated.
