### ISSUE TITLE
Error on executing sql during installation

### ISSUE THREAD

**Issue by okiewardoyo** [khodakhah/nodcms#13]
I just try to install nodcms, but when it try to install sql , it alway say "There have been attempts to setup the database on tokm4153_nodcms and tokm4153_ci but all failed!"

Any solution?

Complete error:
"There have been attempts to setup the database on tokm4153_nodcms and tokm4153_ci but all failed!"
The database tokm4153_nodcms is empty and ready for installation.
The SQL installation script:
`ET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS`ci_sessions`(
`id`varchar(40) NOT NULL,
`ip_address`varchar(45) NOT NULL,
`timestamp`int(10) unsigned NOT NULL DEFAULT '0',
`data`blob NOT NULL,
  KEY`ci_sessions_timestamp`(`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- Dumping structure for table nodcms_demo.comments
DROP TABLE IF EXISTS`comments`;
CREATE TABLE IF NOT EXISTS`comments`(
`bla
bla
bla
bla
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
`

**Comment by khodakhah** [comment]
Hi,
You can create your database manually.
Then, copy the text in the SQL file "<b>install/installer/masks/nodcms.sql</b>" manually in to your database.
Then, make your <b>config/database.php</b> file.
Use the below link:
[Manual installation](http://www.nodcms.com/en/extension/18/install-nodCMS-database)

**Comment by okiewardoyo** [comment]
Thanks, ;)

**Comment by okiewardoyo** [comment]
I try to install it on another host and error still occured.
Did you fix it??
i should it manually install it by created database.php , put it on nodcms-master/cofig/database.php and put it on nodmcs-master/nodcms/config/database.php

And now i can not login using your default admin, username: admin, password: 123456

**Comment by khodakhah** [comment]
New version of NodCMS updated.
