### ISSUE TITLE
Blank white page installer on Localhost XAMPP 7.0.2 Windows 10

### ISSUE THREAD

**Issue by okiewardoyo** [khodakhah/nodcms#16]
I'm trying to install this nodcms on my localhost with xampp 7.0.2, windows 10,  when open http://localhost/nodcms/, it redirect to http://localhost/nodcms/install/ folder, but show nothing , just blank white page.
i tried to echo "INST_BASEDIR.INST_RUNFOLDER.INST_RUNINSTALL", then it shows **E:\XAMPP\htdocs\nodcms\install\installer/installer.php**
I think it cause my install page became blank white page.
but,
i tried change the code:
**define('INST_RUNFOLDER', 'installer/');**
become:
**define('INST_RUNFOLDER', 'installer\\');**
, But it still show blank white page, any idea? thanks

**Comment by khodakhah** [comment]
Hi Mr. Wardoyo,

after install it should be work.(redirect to index.php). You should check your `config/database.php` file. If it doesn't exists then run redirect code to installer folder.
You can try manual installation with below link:
[install nodCMS database](http://www.nodcms.com/en/extension/18/install-nodCMS-database)

**Comment by okiewardoyo** [comment]
Until now i still could not figure out,
i re-extracted downloaded nodcms.
And open it on my localhost http://localhost/nodcms
then it redirected to http://localhost/nodcms/install/
but it just show blank white page, ;)
----
then i try to copy install/index.php to install/index-1.php and modificate this, like below:
`<?php
    define('INST_RUNSCRIPT', pathinfo(__FILE__, PATHINFO_BASENAME));
    define('INST_BASEDIR',	 str_replace(INST_RUNSCRIPT, '', __FILE__));
    define('INST_RUNFOLDER', 'installer/');
	define('INST_RUNINSTALL', 'installer.php');
    if (is_dir(INST_BASEDIR.INST_RUNFOLDER) && is_readable(INST_BASEDIR.INST_RUNFOLDER.INST_RUNINSTALL)){
        //require(INST_BASEDIR.INST_RUNFOLDER.INST_RUNINSTALL); 
		echo "The required file is ".INST_BASEDIR.INST_RUNFOLDER.INST_RUNINSTALL."<br/><br/>";
	}

	echo "INST_RUNSCRIPT = ".INST_RUNSCRIPT."<br/>";
	echo "INST_BASEDIR = ".INST_BASEDIR."<br/>";
	echo "INST_RUNFOLDER = ".INST_RUNFOLDER."<br/>";
	echo "INST_RUNINSTALL = ".INST_RUNINSTALL."<br/><br/>";
	
	if (is_dir(INST_BASEDIR.INST_RUNFOLDER))
		echo "INST_BASEDIR.INST_RUNFOLDER is a directory <br/>";
	
	if(is_readable(INST_BASEDIR.INST_RUNFOLDER.INST_RUNINSTALL))
		echo "INST_BASEDIR.INST_RUNFOLDER.INST_RUNINSTALL is readable <br/>";
    /* ================================================================= */
?>


<h1>Installed Free nodCMS Script successful!</h1>
<a href="../">Go to nodCMS</a>
`
==========
And the result:
```
The required file is E:\XAMPP\htdocs\nodcms\install\installer/installer.php

INST_RUNSCRIPT = index-okie.php
INST_BASEDIR = E:\XAMPP\htdocs\nodcms\install\
INST_RUNFOLDER = installer/
INST_RUNINSTALL = installer.php

INST_BASEDIR.INST_RUNFOLDER is a directory
INST_BASEDIR.INST_RUNFOLDER.INST_RUNINSTALL is readable 
```

**Comment by okiewardoyo** [comment]
I'm curious why it just display blank white page,
so, i go to nodcms/install/installer/configuration.php,
and set some configuration variable below:
'show_php_error_messages' => true,
'show_database_error_messages' => true,

then, the result is below:
`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Inst_Masks has a deprecated constructor in E:\XAMPP\htdocs\nodcms\install\installer\assets\class.masks.php on line 15

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Inst_HtmlMaker has a deprecated constructor in E:\XAMPP\htdocs\nodcms\install\installer\assets\class.htmlmaker.php on line 15

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Inst_Databases has a deprecated constructor in E:\XAMPP\htdocs\nodcms\install\installer\assets\class.databases.php on line 15

Fatal error: Uncaught Error: Call to undefined function mcrypt_ecb() in E:\XAMPP\htdocs\nodcms\install\installer\assets\helper.functions.php:290 Stack trace: #0 E:\XAMPP\htdocs\nodcms\install\installer\assets\helper.sessions.php(95): Encrypt('') #1 E:\XAMPP\htdocs\nodcms\install\installer\installer.php(44): require('E:\\XAMPP\\htdocs...') #2 E:\XAMPP\htdocs\nodcms\install\index.php(9): require('E:\\XAMPP\\htdocs...') #3 {main} thrown in E:\XAMPP\htdocs\nodcms\install\installer\assets\helper.functions.php on line 290`

**Comment by khodakhah** [comment]
I know the installer is not powerful and doesn't work in all version of XAMPPs
Make sure the installer will change in the near future.

But now;
## Please try the manual way to install your nodcms:

1. Go to `http://localhost/phpmyadmin` and make there a new empty database(Set "Collation" on utf8_general_ci)
2. Choose your new database and click on Import
3. In "**File to Import**" section brows your mask file in nodcms root(`nodcms/install/installer/masks/nodcms.sql`) and click on **GO**
4. Go to `nodcms/nodcms/config/`
5. Rename the file `database_manual.php` to `database.php`
6. Open `database.php` with nodpad or nodpad++
7. Inster your database name in line 81 between the last two quotation marks (`'database' => 'YOUR DATABASE NAME',`)

### If your your MySQL on your local host have a password:

8. Inter your password in line 80 between the last two quotation marks.(`'password' => 'YOUR PASSWORD',`)

Save your changes in `database.php` and try your nodcms :wink:

**Comment by okiewardoyo** [comment]
OK, for now the manual install is best solution, ;)
