### ISSUE TITLE
Problem at contact form

### ISSUE THREAD

**Issue by allado** [khodakhah/nodcms#17]
when I use the contact form returns me error page 404

http://demo.nodcms.com/en/contact

return: http://demo.nodcms.com/sendemail.

what is happening ?

on your site the same thing happens

**Comment by khodakhah** [comment]
Hi, 
The URL of actions changed. Contact form action should be 
`action="http://demo.nodcms.com/en/contact"`
you can edit it on `"nodcms/views/nodcms_general/contact.php" Line 69`. Just remove action value like this: `action=""`

I will fix it but with new version. new version coming soon :wink: :smiley:

**Comment by allado** [comment]
Thanks... I fix it.... Good Job !!!
