### ISSUE TITLE
How remapped URL content ?

### ISSUE THREAD

**Issue by allado** [khodakhah/nodcms#18]
How remapped new URL content created ?

Example:

mysite.com/extension/37     to     mysite.com/mycustomURL.

Best Regards.

**Comment by khodakhah** [comment]
What do you want put instead of "mycustomeURL"?

**Comment by allado** [comment]
yes...mycustomeURL  ... modify route.php  .. thats ok ?

**Comment by khodakhah** [comment]
yes it is on routes.ptp but the extensions working with extension_id. Also you need a number in your URL.
You can change this URL like:
mysite.com/page37
mysite.com/page-37
mysite.com/p-37
mysite.com/id-37

but you can not remove number from URL.
If you want remove number from URL you should make an other unique filed for extensions and change select methods on model and controller.

**Comment by allado** [comment]
Thanks

2016-06-29 6:57 GMT-03:00 Mojtaba <notifications@github.com>:
