### ISSUE TITLE
the post data

### ISSUE THREAD

**Issue by mjiong** [khodakhah/nodcms#19]
@khodakhah hey.I read your source and I like it very much.
And I found that some places you use $_POST to get data.Why all use $this->input->post().

And can I use for my blog free and change some source myself not to tell to you?

**Comment by khodakhah** [comment]
Hi, 
Thank you so much.
$this->input->post() is a library for codeigniter and it's for xss_clean (more safe than $_POST)
You can use NodCMS for free(NOT FOR SELLS) an change it for your self, but if you want change it here on GitHub, i should know what is the changes.

**Comment by mjiong** [comment]
I know the library.
I won't use it for sells.Look at the img

![image](https://cloud.githubusercontent.com/assets/8623362/16451346/025321a6-3e35-11e6-93b1-3aec64a2c506.png)

I delete a class to set the position right.And I change the setting url because it's wrong.
And other I had not found now.

**Comment by khodakhah** [comment]
Ok, no problem.
If you find some bug or problems you can update it here.
Thanks

**Comment by khodakhah** [comment]
New version of NodCMS updated.
