### ISSUE TITLE
frontend doesnot found!!!!

### ISSUE THREAD

**Issue by gnabino1** [khodakhah/nodcms#2]
I installed it but while directing to frontend it shows:
The requested URL /nodcms-master/en was not found on this server.
But backend seems good.

**Comment by khodakhah** [comment]
Is <strong>nodcms-master</strong> your folder's name that you installed the CMS in?

**Comment by emmin** [comment]
the same problem
I installed it but while directing to frontend or backend it shows:
The requested URL /nodcms-master/en was not found on this server.
Please,Help me

**Comment by khodakhah** [comment]
Hi,

I will make an update for NodCMS as soon as possible. I thing in this update your issued will solved.

Thanks

**Comment by emmin** [comment]
Thanks,
i'm waiting for update

**Comment by emmin** [comment]
![farsi](https://cloud.githubusercontent.com/assets/16313405/20707888/4b4e48a0-b625-11e6-86d5-3eeacedcf099.PNG)

**Comment by khodakhah** [comment]
Are you install NodAPS in "farsi" folder?
Did you use the new version?

**Comment by emmin** [comment]
i used a new version,


nodAPS ?!!!



________________________________
De : Mojtaba <notifications@github.com>
Envoyé : samedi 7 janvier 2017 21:20
À : khodakhah/nodcms
Cc : emmin; Comment
Objet : Re: [khodakhah/nodcms] frontend doesnot found!!!! (#2)


Are you install NodAPS in "farsi" folder?
Did you use the new version?

-

**Comment by khodakhah** [comment]
New version of NodCMS updated.
