### ISSUE TITLE
Blank page on frontend

### ISSUE THREAD

**Issue by hieu-rhodium** [khodakhah/nodcms#21]
Hi khodakhah,

After installed Nodcms, frontend not showing but backend still showing and I can sign in it. I don't know why frontend not showing.

May you help me?

Thank you very much!

**Comment by khodakhah** [comment]
Hi,
Thank you for using.
Check the log files in nodcms/logs/ and tell me the errors

**Comment by hieu-rhodium** [comment]
Thanks for reply,

I openned the log files in nodcms/logs and this error:

INFO - 2016-07-01 14:38:30 --> Config Class Initialized
INFO - 2016-07-01 14:38:30 --> Hooks Class Initialized
DEBUG - 2016-07-01 14:38:30 --> UTF-8 Support Enabled
INFO - 2016-07-01 14:38:30 --> Utf8 Class Initialized
INFO - 2016-07-01 14:38:30 --> URI Class Initialized
DEBUG - 2016-07-01 14:38:30 --> No URI present. Default controller set.
INFO - 2016-07-01 14:38:30 --> Router Class Initialized
INFO - 2016-07-01 14:38:30 --> Output Class Initialized
INFO - 2016-07-01 14:38:30 --> Security Class Initialized
DEBUG - 2016-07-01 14:38:30 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-07-01 14:38:30 --> Input Class Initialized
INFO - 2016-07-01 14:38:30 --> Language Class Initialized
ERROR - 2016-07-01 14:38:30 --> Severity: Parsing Error --> syntax error, unexpected T_FUNCTION, expecting ')' D:\vinh_data\php_code_vinh\ecommerce\nodcms\controllers\Nodcms_general.php 403
INFO - 2016-07-01 14:38:43 --> Config Class Initialized
INFO - 2016-07-01 14:38:43 --> Hooks Class Initialized
DEBUG - 2016-07-01 14:38:43 --> UTF-8 Support Enabled
INFO - 2016-07-01 14:38:43 --> Utf8 Class Initialized
INFO - 2016-07-01 14:38:43 --> URI Class Initialized
INFO - 2016-07-01 14:38:43 --> Router Class Initialized
INFO - 2016-07-01 14:38:43 --> Output Class Initialized
INFO - 2016-07-01 14:38:43 --> Security Class Initialized
DEBUG - 2016-07-01 14:38:43 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-07-01 14:38:43 --> Input Class Initialized
INFO - 2016-07-01 14:38:43 --> Language Class Initialized
INFO - 2016-07-01 14:38:43 --> Loader Class Initialized
DEBUG - 2016-07-01 14:38:43 --> Config file loaded: D:\vinh_data\php_code_vinh\ecommerce\nodcms\config/nodcms.php
INFO - 2016-07-01 14:38:43 --> Helper loaded: url_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: file_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: form_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: text_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: security_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: language_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: cookie_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: captcha_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: image_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: page_type_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: nodcms_general_helper
INFO - 2016-07-01 14:38:43 --> Database Driver Class Initialized
INFO - 2016-07-01 14:38:43 --> Session: Class initialized using 'database' driver.
INFO - 2016-07-01 14:38:43 --> Language file loaded: language/english/pagination_lang.php
INFO - 2016-07-01 14:38:43 --> Pagination Class Initialized
INFO - 2016-07-01 14:38:43 --> Controller Class Initialized
INFO - 2016-07-01 14:38:43 --> Model Class Initialized
INFO - 2016-07-01 14:38:43 --> Model Class Initialized
INFO - 2016-07-01 14:38:43 --> Helper loaded: admin_page_type_helper
INFO - 2016-07-01 14:38:43 --> Helper loaded: nodcms_form_helper
INFO - 2016-07-01 14:38:43 --> Config Class Initialized
INFO - 2016-07-01 14:38:43 --> Hooks Class Initialized
DEBUG - 2016-07-01 14:38:43 --> UTF-8 Support Enabled
INFO - 2016-07-01 14:38:43 --> Utf8 Class Initialized
INFO - 2016-07-01 14:38:43 --> URI Class Initialized
INFO - 2016-07-01 14:38:43 --> Router Class Initialized
INFO - 2016-07-01 14:38:43 --> Output Class Initialized
INFO - 2016-07-01 14:38:43 --> Security Class Initialized
DEBUG - 2016-07-01 14:38:44 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-07-01 14:38:44 --> Input Class Initialized
INFO - 2016-07-01 14:38:44 --> Language Class Initialized
INFO - 2016-07-01 14:38:44 --> Loader Class Initialized
DEBUG - 2016-07-01 14:38:44 --> Config file loaded: D:\vinh_data\php_code_vinh\ecommerce\nodcms\config/nodcms.php
INFO - 2016-07-01 14:38:44 --> Helper loaded: url_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: file_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: form_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: text_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: security_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: language_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: cookie_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: captcha_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: image_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: page_type_helper
INFO - 2016-07-01 14:38:44 --> Helper loaded: nodcms_general_helper
INFO - 2016-07-01 14:38:44 --> Database Driver Class Initialized
INFO - 2016-07-01 14:38:44 --> Session: Class initialized using 'database' driver.
INFO - 2016-07-01 14:38:44 --> Language file loaded: language/english/pagination_lang.php
INFO - 2016-07-01 14:38:44 --> Pagination Class Initialized
INFO - 2016-07-01 14:38:44 --> Controller Class Initialized
INFO - 2016-07-01 14:38:44 --> Model Class Initialized
INFO - 2016-07-01 14:38:44 --> Model Class Initialized
INFO - 2016-07-01 14:38:44 --> Model Class Initialized
INFO - 2016-07-01 14:38:44 --> Language file loaded: language/english/en_lang.php
ERROR - 2016-07-01 14:38:44 --> Could not find the language line "Administration"
ERROR - 2016-07-01 14:38:44 --> Could not find the language line "Sign Panel"
ERROR - 2016-07-01 14:38:44 --> Could not find the language line "Username"
ERROR - 2016-07-01 14:38:44 --> Could not find the language line "This is just for Administrators"
INFO - 2016-07-01 14:38:44 --> File loaded: D:\vinh_data\php_code_vinh\ecommerce\nodcms\views\nodcms_admin_login.php
INFO - 2016-07-01 14:38:44 --> Final output sent to browser
DEBUG - 2016-07-01 14:38:44 --> Total execution time: 0.2524

**Comment by khodakhah** [comment]
New version of NodCMS updated.
