### ISSUE TITLE
Template broken after posting comments in NodCMS !!!

### ISSUE THREAD

**Issue by allado** [khodakhah/nodcms#24]
Hi... please help

When a user adds a comment and then the administrator enabled, the template is unconfigured. what's going on ?

this happens also in clean facilities nodcms !

Please ... see you the problem at: 

http://electricista.enrosario.com.ar/extension/19

**Comment by va1da5** [comment]
It breaks because of this:
`PHP Fatal error:  Call to undefined function mkh_int_fullDate() in /var/www/nodcms-master/nodcms/views/nodcms_general/page_type/news_clumbs_big_pic_extension.php on line 51`
