### ISSUE TITLE
Admin page didn't load

### ISSUE THREAD

**Issue by tintutech** [khodakhah/nodcms#25]
Hi Team,

I manually installed nodcms on my local system and frontend  is ok.
But the admin page is not loaded.
The error log shows 
"Severity: Compile Error --> Cannot redeclare mk_use_uploadbox() (previously declared in /Applications/MAMP/htdocs/nodcms/nodcms/helpers/NodCMS_form_helper.php:3) /Applications/MAMP/htdocs/nodcms/nodcms/helpers/nodcms_form_helper.php 39"

Appreciate your support for this

**Comment by ashokbhamla** [comment]
Fatal error: Cannot redeclare mk_use_uploadbox() (previously declared in /Applications/XAMPP/xamppfiles/htdocs/nodcms/nodcms/helpers/NodCMS_form_helper.php:3) in /Applications/XAMPP/xamppfiles/htdocs/nodcms/nodcms/helpers/nodcms_form_helper.php on line 39

**Comment by syscoid** [comment]
this a simple problem, u must declare this fuction.
see sample on nodcms_from_helper.php
function mk_use_uploadbox($this){
    // ... original your function
} 

Replace like this on all fuction:
if (!function_exists('mk_use_uploadbox')) {
function mk_use_uploadbox($this){
    // ... proceed to declare your function
  }
}

**Comment by khodakhah** [comment]
New version of NodCMS updated.
