### ISSUE TITLE
Admin page not load

### ISSUE THREAD

**Issue by ashokbhamla** [khodakhah/nodcms#27]
Fatal error: Cannot redeclare mk_use_uploadbox() (previously declared in /Applications/XAMPP/xamppfiles/htdocs/nodcms/nodcms/helpers/NodCMS_form_helper.php:3) in /Applications/XAMPP/xamppfiles/htdocs/nodcms/nodcms/helpers/nodcms_form_helper.php on line 39

Looking for help

**Comment by khodakhah** [comment]
New version of NodCMS updated.
