### ISSUE TITLE
please send me the script for face book and google login for   fronted users

### ISSUE THREAD

**Issue by erpremgupta** [khodakhah/nodcms#28]
hello there ,

please send me the  script for the  user login with facebook and google 

i am try to fix that   but  i  cant .
its very urgent .

**Comment by erpremgupta** [comment]
its very urgent ...

**Comment by erpremgupta** [comment]
Hey khodakhah,
Are you there?

why you not yet reply my issue .

Please send me the script

**Comment by khodakhah** [comment]
Hi,

If you want something more than what in NodCMS is, you should pay for that.
Do you want to pay? Send me an email.

Thanks

**Comment by erpremgupta** [comment]
Yes ,How much cost you want for that script ,

**Comment by khodakhah** [comment]
Hi,

Please send me your request via email. Then I will send back your email with the price.

Thanks

**Comment by erpremgupta** [comment]
what is the email where is send request ?
Please send me the  email.
Thanks
Prem
 here is the my email :-erpremgupta@gmail.com
