### ISSUE TITLE
Passowrd

### ISSUE THREAD

**Issue by joaovelozo** [khodakhah/nodcms#39]
The admin password 123456 does not work.

**Comment by DEV-byoos** [comment]
joaovelozo send me an email I send you the latest version

Gabriel

**Comment by ashokbhamla** [comment]
Please send me latest version , I am fan of your cms

**Comment by joaovelozo** [comment]
joaovelozo@gmail.com

**Comment by joaovelozo** [comment]
> joaovelozo send me an email I send you the latest version
> 
> Gabriel

joaovelozo@gmail.com

**Comment by khodakhah** [comment]
Thank you for your report. I'll solve it as soon as possible.

**Comment by khodakhah** [comment]
It has been solved with the version. Whit the new installation.
