### ISSUE TITLE
Admin area

### ISSUE THREAD

**Issue by AndrewLCR** [khodakhah/nodcms#4]
How to access the admin area?

**Comment by khodakhah** [comment]
www.your-domain.com/admin

**Comment by conurus** [comment]
Sorry what was the default admin username/password?

**Comment by khodakhah** [comment]
username: admin
password: 123456

**Comment by gesmit** [comment]
Can't access the admin area on a new fresh install, get a partial 404, last line is 
    <link href="

**Comment by khodakhah** [comment]
Unfortunately I couldn't find a problem, that you say.
Please reinstall the CMS. If you see again a problem, please send it with more Information to me.

**Comment by khodakhah** [comment]
New version of NodCMS updated.
