### ISSUE TITLE
migration_nodcms_php5-6_to_php7-3

### ISSUE THREAD

**Issue by DEV-byoos** [khodakhah/nodcms#40]
Hello,
We have migrated the NodCMS application to PHP7.3 and BCRYPT security, can we send the compilation to an email?

kind regards 
Gabriel

**Comment by DEV-byoos** [comment]
available here  https://github.com/DEV-byoos/nodcms_v2
repository  DEV-byoos
thanks for your comment

Best regards
Gabriel

**Comment by khodakhah** [comment]
Hi, 
The new version is right here.
Best Regards
Mojtaba
