### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by mstsargin** [khodakhah/nodcms#45]
I try to install nodcms on my site but mysql hostname get this error " The Host Name field must contain just English letters and underline only."

**Comment by mstsargin** [comment]
my hostname is sql204.epizy.com

**Comment by khodakhah** [comment]
Hi, Thank you for your report. I'll solve it ASAP and send you a notification message.

**Comment by mstsargin** [comment]
When will the problem solved?

**Comment by khodakhah** [comment]
With the last update, the issue has been resolved.
