### ISSUE TITLE
Unable to run, says "Your application folder path does not appear to be set correctly"

### ISSUE THREAD

**Issue by rakeshwsn** [khodakhah/nodcms#47]
I followed the installation instructions in the readme. However it shows "Your application folder path does not appear to be set correctly" error and exits.

Kindly suggest me a step by step method.

**Comment by DEV-byoos** [comment]
hello Rakesh,

see  issue " 48 et 49    please send me your results
support@byoosdigital.com

**Comment by khodakhah** [comment]
Since v3.0 the application root folder for HTTP requests should be set on `public/` directory instead of the root. This info has been written in README.md

Thanks for your report.
