### ISSUE TITLE
admin area does not scroll down

### ISSUE THREAD

**Issue by beginnerFun** [khodakhah/nodcms#5]
in the admin panel i couldnt scroll down to see the chart !
![image](https://cloud.githubusercontent.com/assets/15382838/10823965/659fc728-7e73-11e5-87fd-0d6ab5dde370.png)
 this issue get worst in the other sections too 
![image](https://cloud.githubusercontent.com/assets/15382838/10824059/f627f680-7e73-11e5-9cb1-f6f954a7702b.png)
 its supposed to like in the demo mode like this pic 
![image](https://cloud.githubusercontent.com/assets/15382838/10824070/1278b018-7e74-11e5-9d87-d7f1ada93569.png)

how can i fix this ?
tnx in advanced

**Comment by khodakhah** [comment]
I thing, the problem is "<b>niceScroll</b>".
I removed it from "<b>backend document</b>"
I wish it works better now.
You can see the change on this link: https://github.com/khodakhah/nodcms/commit/6f46cdfb930e5789c9814957c4a52f02c00daf7d

**Comment by khodakhah** [comment]
New version of NodCMS updated.
