### ISSUE TITLE
url copy does not work

### ISSUE THREAD

**Issue by beginnerFun** [khodakhah/nodcms#6]
the url copy does not work
![image](https://cloud.githubusercontent.com/assets/15382838/10851038/1627eff6-7f3e-11e5-8f67-928223a49d2b.png)

**Comment by khodakhah** [comment]
It works!

After click on the "<b>URL Copy</b>", you should close the <b>Modal (Choose uploaded image)</b>. Then you can see: the URL of image copied in your field.

**Comment by khodakhah** [comment]
New version of NodCMS updated.
