### ISSUE TITLE
Error on backend_lang.php files

### ISSUE THREAD

**Issue by eSkiSo** [khodakhah/nodcms#7]
I was getting an erro trying to access the admin backend, traced it back to the backend_lang.php files, had to do an Enter after <?php because it was giving unexpected end of file

Also had errors installing the database, had to do it manually and then alter the installer to not check db.

**Comment by khodakhah** [comment]
I tested this and once installed the CMS. It works quite well.
But I have edited the file "<b>backend_lang.php</b>". Maybe now works better for you. 
You can send me more information with email if you want. Maybe I can better help you!

**Comment by khodakhah** [comment]
New version of NodCMS updated.
