### ISSUE TITLE
Blank page after install

### ISSUE THREAD

**Issue by babarazvan** [khodakhah/nodcms#8]
I just made an installation on root directory and on a subfolder, but for both of them i have blank page.
Have any ideea.?
Thanks

**Comment by khodakhah** [comment]
I I tested the "<b>Installation</b>" and it works quite well. I don't have any idea what happened! But you can test "<a href="http://www.nodcms.com/en/extension/17/Installation">Manual Way</a>".
If it's on the host, I can help you to install. Send me an email!

**Comment by khodakhah** [comment]
I found that bug, that you said. I debug it. Sorry for previous answers.

You can see the changes in this link: https://github.com/khodakhah/nodcms/commit/3f177ee61a7b903aa5d37db5acc03c21af3d8faf

**Comment by floridacoder** [comment]
Same problem, after manual installation it only shows blank page on home and admin url.

**Comment by khodakhah** [comment]
What is your PHP version?

**Comment by khodakhah** [comment]
New version of NodCMS updated.
