### ISSUE TITLE
Problem this installation

### ISSUE THREAD

**Issue by SergeTkach** [khodakhah/nodcms#80]
Hello!
I have tried to install NodCMS. And there are some problem

1. Don't require styles
2. Some troubles with steps links https://nodcms.loc/index.php/installer/installer/license

Look at screenshotes, please!

[https://ibb.co/HF5SkNT](https://ibb.co/HF5SkNT)
[https://ibb.co/HF5SkNT](https://ibb.co/CBgwztx)

**Comment by khodakhah** [comment]
Hi, 

Thanks for the messeage.
Do you have any log files?

**Comment by SergeTkach** [comment]
Yes, I have. There is an error only.

CRITICAL - 2022-04-06 23:58:35 --> Use of undefined constant base_url - assumed 'base_url' (this will throw an Error in a future version of PHP)
#0 /home/www/sites/try/nodcms.loc/nodcms-installer/Controllers/Installer.php(81): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', '/home/www/sites...', 81, Array)
#1 /home/www/sites/try/nodcms.loc/vendor/codeigniter4/framework/system/CodeIgniter.php(809): NodCMS\Installer\Controllers\Installer->__construct()
#2 /home/www/sites/try/nodcms.loc/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#3 /home/www/sites/try/nodcms.loc/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /home/www/sites/try/nodcms.loc/public/index.php(80): CodeIgniter\CodeIgniter->run()
#5 {main}

**Comment by khodakhah** [comment]
I'm sorry but I couldn't reproduce the error or problem. You have probably some issues with your environment. 

Here is some recommendation: 
- Make sure that the Apache, PHP, and MySQL running on your environment correctly.
- Make sure that you took the latest version of NodCMS.
- Make sure that your Apache configuration has been correctly set. Specifically, it allows .htaccess files.

To be sure that your environment has some sort of problems, you can try the NodCMS on a  managed Linux Webhosting.

Please, let me know if you found the problem.
