### ISSUE TITLE
INSTALLER ERROR: ErrorException is_file(): open_basedir restriction in effect. File(/NodCMS\Installer/overview.php) is not within the allowed path(s):

### ISSUE THREAD

**Issue by SIENSIS** [khodakhah/nodcms#83]
CI4 Requirements check
Subdomain in plesk server
Securized via LetsEncrypt SSL

is_file(): open_basedir restriction in effect. File(/NodCMS\Installer/overview.php) is not within the allowed path(s): (/var/www/vhosts/nodcms.domain.com/:/tmp/) 

SYSTEMPATH/View/View.php at line 192

**Comment by khodakhah** [comment]
Hi, 
It seems that you have an issue with the settings on your hosting. Please try [this solution](https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths).

Thanks.
