### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by maxell623062** [khodakhah/nodcms#84]
I have not used nod cms since the early versions which were so easy to install, drop in your folder and off you go. The latest versions however I cannot get my head around installing and I don't find the guides any help which is a shame for such a great project. Even using composer it does not work. I don't understand the director structure or what goes where. Any help or advice would be appreciated.

**Comment by DEV-byoos** [comment]
hello dev,

Download the improved version byoosdigital.com on gitHub
https://github.com/DEV-byoos/nodcms_v3-2-2c

read the file 
nodcms-portage-ci415_v3-2-1-5.txt at the root of the project

Porting nodcms_3-2-1-5 to CodeIgniter 4.1.5 then improving PAGINATION, AUTH, DISPLAY of articles 2021/11/30 to 2021/12/24

and mutilanguage support

Sincerely
Gabriel

**Comment by khodakhah** [comment]
Hi @maxell623062 

> Important: your domain should point to the `/public/` directory.

To understand the directory structure you need to learn [CodeIgniter Application Structure](https://codeigniter.com/user_guide/concepts/structure.html). 
In NodCMS each directory with the prefix `nodcms-` is a module and works as `app` directory(just as described in CodeIgniter docs).
By the way, you are able to use the NodCMS in old ways. Just download [NodCMS-Bundle](https://github.com/khodakhah/nodcms-bundle).

Thanks
