### ISSUE TITLE
 UPdate CI4.2 - BCRYPT and installer #1 

### ISSUE THREAD

**Issue by DEV-byoos** [khodakhah/nodcms#88]
Hello dev's

This version of NodCms 3.2.2c includes substantial improvements, including the switch to AUTH bycrypt PHP function password_hash() to replace **MD5 deprecated for 10 years...**

other improvements such as the possibility to execute outside the /root/ location

Installer keeps the "admin" password in MD5, then switches to Bcrypt at first login, in bcrypt hash mode for all new users

another improvement on the default multilingual management in /en

and many other bug fixes

Good use
gabriel

**Comment by khodakhah** [comment]
Thanks for the info.
