### ISSUE TITLE
Dropdown Menu

### ISSUE THREAD

**Issue by wildanSawaludin** [khodakhah/nodcms#9]
Can add a dropdown menu in this cms ?

**Comment by khodakhah** [comment]
Yes, from now! :wink:

https://github.com/khodakhah/nodcms/commit/bb88dcfbe4d9555d2f98b490cdf26aa5ca9d1689

**Comment by wildanSawaludin** [comment]
Hi,
i have redownloaded with new repository, but when i try to new installation the step for "Install Database Tables" got the message "There has been attempt to setup the database on nodcms_db but failed!"

can you resolved ? :)

**Comment by khodakhah** [comment]
Maybe you use the last DB, that you before used it. DB should be empty!

**Comment by erpremgupta** [comment]
I love the cms its look like very user friendly but limited feature 
it would be few  more update needed .

**Comment by khodakhah** [comment]
New version of NodCMS updated.
